# Generated by Django 2.1.5 on 2019-04-26 14:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='收款公司名称')),
                ('c_appid', models.CharField(max_length=32, verbose_name='商家支付宝appid')),
                ('alipay_public_key', models.TextField(verbose_name='支付宝公钥')),
                ('c_private_key', models.TextField(verbose_name='商家私钥')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活状态')),
                ('last_time', models.DateTimeField(blank=True, null=True, verbose_name='最后收款时间')),
                ('total_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='总收款')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属代理')),
            ],
            options={
                'verbose_name': '支付宝管理',
                'verbose_name_plural': '支付宝管理',
            },
        ),
        migrations.CreateModel(
            name='channelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=32, verbose_name='通道名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通道管理',
                'verbose_name_plural': '通道管理',
            },
        ),
    ]
