# Generated by Django 2.1.5 on 2019-04-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipayinfo',
            name='c_appid',
            field=models.CharField(max_length=32, unique=True, verbose_name='商家支付宝appid'),
        ),
    ]
