# Generated by Django 2.1.5 on 2019-04-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20190426_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.IntegerField(choices=[(3, '通知失败'), (0, '待支付'), (1, '支付成功'), (2, '支付关闭')], default=0, verbose_name='订单状态'),
        ),
    ]
