# Generated by Django 2.1.5 on 2019-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190426_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='支付宝交易号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.IntegerField(choices=[(2, '支付关闭'), (0, '待支付'), (3, '通知失败'), (1, '支付成功')], default=0, verbose_name='订单状态'),
        ),
    ]
