# Generated by Django 2.1.5 on 2019-04-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190426_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(choices=[(4, '财务'), (3, '商户'), (2, '代理'), (1, '管理员'), (5, '观察者')], default=3, verbose_name='用户等级'),
        ),
    ]
