# Generated by Django 2.1.5 on 2019-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190426_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(choices=[(5, '观察者'), (3, '商户'), (2, '代理'), (1, '管理员'), (4, '财务')], default=3, verbose_name='用户等级'),
        ),
    ]
