# Generated by Django 2.1.5 on 2019-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190427_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(choices=[(3, '商户'), (5, '观察者'), (4, '财务'), (1, '管理员'), (2, '代理')], default=3, verbose_name='用户等级'),
        ),
    ]
