# Generated by Django 2.1.5 on 2019-04-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginfo',
            name='log_type',
            field=models.IntegerField(choices=[(0, '登录记录'), (3, '用户记录'), (2, '提现记录'), (1, '订单记录')], verbose_name='操作类型'),
        ),
    ]
