# Generated by Django 2.1.5 on 2019-04-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spuser', '0003_auto_20190426_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginfo',
            name='log_type',
            field=models.IntegerField(choices=[(1, '订单记录'), (3, '用户记录'), (0, '登录记录'), (2, '提现记录')], verbose_name='操作类型'),
        ),
    ]
